import { supabase, DeliveryAddress, OrderItem } from "@/lib/supabase";
import { CartItem } from "@/lib/store";

interface PlaceOrderParams {
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  deliveryAddress: DeliveryAddress;
  cartItems: CartItem[];
  totalAmount: number;
}

interface PlaceOrderResult {
  success: boolean;
  orderNumber?: string;
  orderId?: string;
  error?: string;
}

export const usePlaceOrder = () => {
  const placeOrder = async (params: PlaceOrderParams): Promise<PlaceOrderResult> => {
    const { customerName, customerEmail, customerPhone, deliveryAddress, cartItems, totalAmount } = params;

    try {
      // 1. Upsert customer by email
      const { data: customerData, error: customerError } = await supabase
        .from("customers")
        .upsert(
          { name: customerName, email: customerEmail, phone: customerPhone },
          { onConflict: "email", ignoreDuplicates: false }
        )
        .select("id")
        .single();

      if (customerError) throw customerError;

      // 2. Build order items array
      const items: OrderItem[] = cartItems.map((item) => ({
        product_id: item.product.id,
        name: item.product.name,
        color: item.color,
        color_hex: item.product.colors.find((c) => c.name === item.color)?.hex ?? "#000",
        size: item.size,
        qty: item.quantity,
        price: item.product.price,
        image_url: item.product.image,
      }));

      // 3. Insert order — order_number auto-generated by DB trigger as EP-2025-XXXX
      const { data: orderData, error: orderError } = await supabase
        .from("orders")
        .insert({
          customer_id: customerData.id,
          customer_name: customerName,
          customer_email: customerEmail,
          customer_phone: customerPhone,
          items,
          total_amount: totalAmount,
          delivery_address: deliveryAddress,
          payment_status: "pending",
          order_status: "placed",
          order_number: "", // will be set by DB trigger
        })
        .select("id, order_number")
        .single();

      if (orderError) throw orderError;

      return {
        success: true,
        orderNumber: orderData.order_number,
        orderId: orderData.id,
      };
    } catch (err: unknown) {
      console.error("Order placement error:", err);
      return {
        success: false,
        error: err instanceof Error ? err.message : "Failed to place order",
      };
    }
  };

  return { placeOrder };
};
